# Generated by Django 4.1.7 on 2023-03-29 18:52

from django.db import migrations, models
import score.models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateField(default=score.models.get_today),
        ),
    ]
