# Generated by Django 4.1.7 on 2024-05-10 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_add_default_categories'),
        ('score', '0002_alter_score_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='category.category'),
        ),
    ]
