# Generated by Django 4.1.7 on 2024-05-11 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_get_started_first_screen', models.BooleanField(default=False, verbose_name="Нажал 'поехали' на первом экране")),
                ('clicked_view_example_second_screen', models.BooleanField(default=False, verbose_name="Нажал 'смотреть пример' на втором экране")),
                ('clicked_next_second_screen', models.BooleanField(default=False, verbose_name="Нажал 'далее' на втором экране")),
                ('clicked_add_own_category_third_screen', models.BooleanField(default=False, verbose_name="Нажал 'добавить свою категорию' на третьем экране")),
                ('clicked_next_with_categories_third_screen', models.BooleanField(default=False, verbose_name="Нажал 'далее' на третьем экране с категориями")),
                ('clicked_time_selection_onboarding', models.BooleanField(default=False, verbose_name='Нажал на выбор времени в онбординге')),
                ('completed_all_assessments', models.BooleanField(default=False, verbose_name='Прошел оценку всех параметров')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metric', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статистика онбординга',
                'verbose_name_plural': 'Статистики онбордингов',
            },
        ),
    ]
