# Generated by Django 4.1.7 on 2024-05-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='completed_all_assessments',
        ),
    ]
