# Generated by Django 4.1.7 on 2023-03-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('priority', models.IntegerField(default=1)),
                ('description', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
