# Generated by Django 4.1.7 on 2024-05-10 17:18

from django.db import migrations

def create_default_categories(apps, schema_editor):
    category_model = apps.get_model('category', 'Category')
    DEFAULT_CATEGORIES = (
        'Cпорт',
        'Питание',
        'Сон',
        'Отдых'
    )
    for category_name in DEFAULT_CATEGORIES:
        category_model.objects.create(
            name=category_name,
            priority=1,
            description='',
            is_active=True,
            is_default=True,
            user=None
        )


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_is_default_alter_category_user'),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]
