# Generated by Django 4.1.7 on 2024-05-11 23:43

from django.db import migrations

def create_prod_category(apps, schema_editor):
    category_model = apps.get_model('category', 'Category')
    category_model.objects.create(
        name='Продуктивность',
        priority=1,
        description='',
        is_active=True,
        is_default=True,
        user=None,
        color='#32CD32'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_category_color'),
    ]

    operations = [
        migrations.RunPython(create_prod_category),
    ]
