# Generated by Django 4.1.7 on 2024-05-11 23:52

from django.db import migrations

def set_colors_for_default_categories(apps, schema_editor):
    category_model = apps.get_model('category', 'Category')
    default_categories = category_model.objects.filter(is_default=True)
    name_color_map = {
        'Питание': '#5e7e66',
        'Cпорт': '#d76e16',
        'Сон': '#0a093f',
        'Отдых': '#63a1af'
    }
    for name, color in name_color_map.items():
        category = default_categories.filter(name=name).first()
        category.color = color
        category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_create_prod_default_category'),
    ]

    operations = [
        migrations.RunPython(set_colors_for_default_categories)
    ]
